// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OurFuss.Data.Postgre.Db;

#nullable disable

namespace OurFuss.Data.Postgre.Migrations
{
    [DbContext(typeof(OurFussContextPostgre))]
    [Migration("20250110130406_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OurFuss.Core.Sections.Telegram.Models.Entities.TelegramAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("ChatId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FullName");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Modified");

                    b.Property<int>("TelegramRole")
                        .HasColumnType("integer")
                        .HasColumnName("TelegramRole");

                    b.Property<int>("UserMemberStatus")
                        .HasColumnType("integer")
                        .HasColumnName("UserMemberStatus");

                    b.HasKey("Id");

                    b.ToTable("Account", "tg");
                });
#pragma warning restore 612, 618
        }
    }
}
