// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OurFuss.Data.Postgre.Db;

#nullable disable

namespace OurFuss.Data.Postgre.Migrations
{
    [DbContext(typeof(OurFussContextPostgre))]
    [Migration("20250116155854_Q2")]
    partial class Q2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OurFuss.Core.Sections.Events.Models.Entities.EventCustomPhotoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FileId");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("FileSize");

                    b.Property<string>("FileUniqueId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FileUniqueId");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("Height");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Modified");

                    b.Property<Guid>("UserEventCustomId")
                        .HasColumnType("uuid");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("Width");

                    b.HasKey("Id");

                    b.HasIndex("UserEventCustomId");

                    b.ToTable("EventCustomPhoto", "evnt");
                });

            modelBuilder.Entity("OurFuss.Core.Sections.Events.Models.Entities.UserEventCustomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Modified");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Text");

                    b.HasKey("Id");

                    b.ToTable("UserEventCustom", "evnt");
                });

            modelBuilder.Entity("OurFuss.Core.Sections.Telegram.Models.Entities.TelegramAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("ChatId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FullName");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Modified");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("TelegramId");

                    b.Property<int>("TelegramRole")
                        .HasColumnType("integer")
                        .HasColumnName("TelegramRole");

                    b.Property<int>("UserMemberStatus")
                        .HasColumnType("integer")
                        .HasColumnName("UserMemberStatus");

                    b.HasKey("Id");

                    b.ToTable("Account", "tg");
                });

            modelBuilder.Entity("OurFuss.Core.Sections.Events.Models.Entities.EventCustomPhotoEntity", b =>
                {
                    b.HasOne("OurFuss.Core.Sections.Events.Models.Entities.UserEventCustomEntity", "UserEventCustom")
                        .WithMany("Photos")
                        .HasForeignKey("UserEventCustomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEventCustom");
                });

            modelBuilder.Entity("OurFuss.Core.Sections.Events.Models.Entities.UserEventCustomEntity", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
